name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Build project
      run: cargo build --release

    - name: Upload artifact (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-latest-heaven
        path: target/release/heaven

    - name: Upload artifact (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v2
      with:
        name: macos-latest-heaven
        path: target/release/heaven

    - name: Upload artifact (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: windows-latest-heaven
        path: target/release/heaven.exe

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifact (Linux)
      uses: actions/download-artifact@v2
      with:
        name: ubuntu-latest-heaven
        path: artifacts/ubuntu

    - name: Download artifact (macOS)
      uses: actions/download-artifact@v2
      with:
        name: macos-latest-heaven
        path: artifacts/macos

    - name: Download artifact (Windows)
      uses: actions/download-artifact@v2
      with:
        name: windows-latest-heaven
        path: artifacts/windows

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          artifacts/ubuntu/*
          artifacts/macos/*
          artifacts/windows/*
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: |
          New release ${{ github.ref }} is available.
        draft: false
        prerelease: false
